E0s: '{1: -4.870504619050359, 6: -0.974100923810072, 7: -1.9482018476201453, 35: -3.930680896420158,
  82: -1.4782899863050427}'
MLP_irreps: 16x0e
amsgrad: true
avg_num_neighbors: 71.85360717773438
batch_size: 2
charges_key: charges
checkpoints_dir: ''
clip_grad: 10
compute_avg_num_neighbors: false
compute_forces: true
compute_stress: true
config_type_weights: '{Default:1.0}'
correlation: 4
default_dtype: float32
device: cpu
dipole_key: dipole
downloads_dir: ''
ema: true
ema_decay: 0.99
energy_key: energy
energy_weight: 10.0
error_table: PerAtomRMSE
eval_interval: 2
forces_key: forces
forces_weight: 1.0
gate: silu
interaction: RealAgnosticResidualInteractionBlock
interaction_first: RealAgnosticResidualInteractionBlock
keep_checkpoints: false
log_dir: ''
log_level: INFO
loss: weighted
lr: 0.01
lr_factor: 0.8
lr_scheduler_gamma: 0.9993
max_L: 1
max_ell: 3
max_num_epochs: 120
model: MACE
model_dir: ''
model_dtype: float32
name: mace
num_channels: 16
num_cutoff_basis: 5
num_interactions: 2
num_radial_basis: 8
optimizer: adam
patience: 20
r_max: 7.0
radial_MLP: '[64, 64, 64]'
restart_latest: false
results_dir: ''
save_cpu: true
scaling: rms_forces_scaling
scheduler: ReduceLROnPlateau
scheduler_patience: 50
seed: 0
start_swa: 1000000000000
stress_key: stress
stress_weight: 0
swa: false
swa_energy_weight: 100
swa_forces_weight: 1
swa_lr: 0.001
swa_stress_weight: 0
test_file: null
train_file: /dodrio/scratch/projects/2022_008/vacanciesFAPbBr3/more_vacancies/Train_MACE/psiflow_internal/context_dir/data_000935.xyz
valid_batch_size: 8
valid_file: null
valid_fraction: 1.0e-12
virials_key: virials
wandb: true
wandb_group: null
wandb_log_hypers:
- num_channels
- max_L
- correlation
- lr
- swa_lr
- weight_decay
- batch_size
- max_num_epochs
- start_swa
- energy_weight
- forces_weight
wandb_name: mace_training
wandb_project: null
weight_decay: 5.0e-07
